language: node_js
sudo: false
node_js:
  - "6"

notifications:
  slack:
    rooms:
      - secure: EeajCzaym71HDZxhGNp9cqTfRHQII5kyMiGSV100o7XxP26cY397GvUXe0fqAEdE++uLJUjpO5EWigMNCK/oD5J9f6j41aoEdNE9AK9dSF3A3IhMUBWd+eYN1jBvqibeWSz95qxoUjbhTNQE3iBb7XqZrqjXlGZpOtYDmOqou2DZcRjevA+iLFlAfWsZ5HE598/LvXBMwkBCnqD3EuhkUCZVqEVd/EN/vk/YUnGmeFB+tTXub1XpzqJSnQZI8ZGgSoF6GWl1f+Py/ndMo3oQB8cQW97hFzPzJgu/aprgyIA5PeaRb9xdlRiZGYSiwn9CG8eYdZmtpBGtAELpRyjps+6/+rYddedvAmXB5mELjAfUD2wpn+F8cmgzNh1vraKcG4SpiN+vXyB6vBWZZIMECNQs5jWJOnKsmHcgUyilG2U9X+dyimoRB1xaOkQN3kPWPpddUAqHtKKbSNw9WD1rybv0wa0wlktm1Tl2zoCfiQHDD1aly2cymAOdw/zQTt0vxy/6+ppbYu+igWNSwyxg/K/BmaqLrmAeUWUCRCX6MnLra/ZSaGCSeKDlwRjcGgOWJxSXAkGTcnmyA57sQguZrFztrNEQom44cloFAjUnkdOrWNbpXFVCeH/GoygE+9NgAtst7pw0PbPPhXpZnl9vCHqOFDfY8Mx1UbDlve6hzx4=
    on_success: always
    on_failure: always
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}"
  email: false

git:
  depth: 3

# whitelist
branches:
  only:
    - master
    - /^v2\..+/

cache:
  directories:
    - "node_modules"

install:
  # Check the size of caches
  - du -sh ./node_modules || true
  # Disable the spinner, it looks bad on Travis
  - npm config set spin false
  # Log HTTP requests
  - npm config set loglevel http
  # Install npm dependencies and ensure that npm cache is not stale
  - npm install

before_script:
  - npm run lint

script:

after_success:

before_deploy:

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    node: "6"
    all_branches: true
    tags: true
